version: '3'
services:
  wms:
    depends_on:
      - db
    image: sogis/geoserver:latest
    build:
      context: ./
      dockerfile: Dockerfile
    command: start.sh
    ports:
      - "8080:8080"
    volumes:
      - "${PWD}/data_dir:/var/local/geoserver"
    restart: always
